#!/usr/bin/env bash
set -euo pipefail

USAGE="Usage: clean_and_convert.sh <source-file-or-url> <source-type> <output-dir>

Convert a source document to a single UTF-8 markdown file in <output-dir>.

Source types: office | html | markdown | notion | confluence | drive | image | gh-issue

Tool selection per source type:
  office  : docling (primary), unstructured (fallback), marker (offline fallback)
  html    : readability+markdownify (primary), pandoc (fallback), lynx (offline)
  markdown: copy verbatim
  notion  : already exported markdown — copy verbatim
  confluence: already exported markdown — copy verbatim
  drive   : expects docx from MCP export — convert via pandoc
  image   : expects pre-captioned markdown stub from caller
  gh-issue: expects JSON from gh CLI — convert to inline markdown

Exits non-zero on hard failure. Warns (does not crash) on missing optional tools.
"

if [[ "${1:-}" == "--help" || $# -lt 3 ]]; then
  echo "$USAGE"
  exit 0
fi

SOURCE="$1"
SOURCE_TYPE="$2"
OUTPUT_DIR="$3"

mkdir -p "$OUTPUT_DIR"

SLUG=$(basename "$SOURCE" | sed 's/\.[^.]*$//' | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g' | sed 's/--*/-/g' | sed 's/^-\|-$//g')
OUTPUT_FILE="$OUTPUT_DIR/${SLUG}.md"

check_tool() {
  local tool="$1"
  local installer="$2"
  if ! command -v "$tool" &>/dev/null; then
    echo "[warn] $tool not found. Install with: $installer" >&2
    return 1
  fi
  return 0
}

convert_office() {
  if check_tool docling "pip install docling"; then
    docling --to markdown --output "$OUTPUT_DIR" "$SOURCE" 2>/dev/null && \
      find "$OUTPUT_DIR" -name "*.md" | head -1 | xargs -I{} mv {} "$OUTPUT_FILE" && return 0
  fi
  echo "[warn] docling failed or not available; trying unstructured" >&2
  if check_tool unstructured "pip install unstructured[pdf]"; then
    python3 -c "
from unstructured.partition.auto import partition
from unstructured.staging.base import elements_to_text
import sys
els = partition(filename=sys.argv[1])
print('\n\n'.join(str(e) for e in els))
" "$SOURCE" > "$OUTPUT_FILE" && return 0
  fi
  echo "[warn] unstructured failed or not available; trying marker" >&2
  if check_tool marker "pip install marker-pdf"; then
    marker_single "$SOURCE" "$OUTPUT_DIR" --batch_multiplier 2 2>/dev/null && \
      find "$OUTPUT_DIR" -name "*.md" | head -1 | xargs -I{} mv {} "$OUTPUT_FILE" && return 0
  fi
  echo "[error] No office converter available. Install docling: pip install docling" >&2
  return 1
}

convert_html() {
  if check_tool python3 "" && python3 -c "import readability, markdownify" 2>/dev/null; then
    python3 -c "
import sys
from readability import Document
import markdownify
with open(sys.argv[1]) as f:
    content = f.read()
doc = Document(content)
md = markdownify.markdownify(doc.summary(), heading_style='ATX')
print(md)
" "$SOURCE" > "$OUTPUT_FILE" && return 0
  fi
  echo "[warn] readability/markdownify not available; trying pandoc" >&2
  if check_tool pandoc "brew install pandoc || apt-get install -y pandoc"; then
    pandoc -f html -t markdown --wrap=none -o "$OUTPUT_FILE" "$SOURCE" && return 0
  fi
  echo "[warn] pandoc not available; trying lynx" >&2
  if check_tool lynx "brew install lynx || apt-get install -y lynx"; then
    lynx -dump -nolist "$SOURCE" > "$OUTPUT_FILE" && return 0
  fi
  echo "[error] No HTML converter available. Install: pip install readability-lxml markdownify" >&2
  return 1
}

convert_markdown() {
  cp "$SOURCE" "$OUTPUT_FILE"
}

convert_drive() {
  if check_tool pandoc "brew install pandoc || apt-get install -y pandoc"; then
    pandoc -f docx -t markdown --wrap=none -o "$OUTPUT_FILE" "$SOURCE" && return 0
  fi
  echo "[error] pandoc required for Drive docx conversion. Install: brew install pandoc" >&2
  return 1
}

convert_gh_issue() {
  python3 -c "
import json, sys
data = json.load(open(sys.argv[1]))
title = data.get('title', 'Untitled')
body = data.get('body', '')
number = data.get('number', '')
url = data.get('url', '')
print(f'# {title}')
print()
if url:
    print(f'Source: {url}')
    print()
print(body)
" "$SOURCE" > "$OUTPUT_FILE"
}

case "$SOURCE_TYPE" in
  office)
    convert_office
    ;;
  html)
    convert_html
    ;;
  markdown|notion|confluence)
    convert_markdown
    ;;
  drive)
    convert_drive
    ;;
  image)
    cp "$SOURCE" "$OUTPUT_DIR/"
    echo "# Image: $(basename "$SOURCE")" > "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "Source file: $(basename "$SOURCE")" >> "$OUTPUT_FILE"
    echo "" >> "$OUTPUT_FILE"
    echo "_Caption and description to be generated by the calling agent._" >> "$OUTPUT_FILE"
    ;;
  gh-issue)
    convert_gh_issue
    ;;
  *)
    echo "[error] Unknown source type: $SOURCE_TYPE" >&2
    exit 1
    ;;
esac

if [[ ! -f "$OUTPUT_FILE" || ! -s "$OUTPUT_FILE" ]]; then
  echo "[error] Conversion produced no output at $OUTPUT_FILE" >&2
  exit 1
fi

echo "$OUTPUT_FILE"
